#!/bin/bash


if [ $# -lt 3 ]; then
    echo "Usage: $0 srcFile0 srcFile1 ... dest ip/ipfile"
    exit 1
fi

#echo "argv num is $#"
len=$#
args=($*)

idest=$(($len - 2))
iIp=$(($len - 1))
dest=${args[${idest}]}
ip=${args[${iIp}]}


if [ ! -f $ip ];then
    echo "$ip" > ~/.ip
else
    cat $ip > ~/.ip
fi


subLen=$(($len-2))
files=${args[*]:0:${subLen}}

while read line
do
    echo "----------- scp [$line]  --------------"
    if [[ $line =~ ^#.* ]]; then
        continue
    fi
    cmd="scp $files root@$line:$dest"
    echo $cmd
    `$cmd`
    if [ $? -eq 0 ]; then
        echo " scp success"
    else
        echo " scp failed"
    fi
    echo "---------- finished ------"
    echo "  "
done < ~/.ip

rm -f ~/.ip
